version: '3'

services:
  twitterbot:
    image: node
    command: ["npm", "start"]
    working_dir: /app
    environment:
      - TWITTERBOT_USERNAME=${TWITTERBOT_USERNAME}
      - TWITTERBOT_RETWEET_QUERY=${TWITTERBOT_RETWEET_QUERY}
      - TWITTERBOT_FAVORITES_QUERY=${TWITTERBOT_FAVORITES_QUERY}
      - TWITTERBOT_CONSUMER_KEY=${TWITTERBOT_CONSUMER_KEY}
      - TWITTERBOT_CONSUMER_SECRET=${TWITTERBOT_CONSUMER_SECRET}
      - TWITTERBOT_ACCESS_TOKEN=${TWITTERBOT_ACCESS_TOKEN}
      - TWITTERBOT_ACCESS_TOKEN_SECRET=${TWITTERBOT_ACCESS_TOKEN_SECRET}
    volumes:
      - ./:/app
    ports:
      - 3000:3000
